import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios"
import HmacSHA256 from 'crypto-js/sha256';

export default function Home() {

  function payMe(){    
    const hash = HmacSHA256("merchant=onxQZvaVQZq&apikey=5cCuzYw1AOUKLFS69ruxRBC6qBAQWFBH&nonce=1386178459&to=1CkSCqyWGtVjok5A5xeGKKyMvpeZMnfEbq&fiat_amount=1", "HOSFvwa9pev8gMk3Cj6q6elKdwSkEPaL");
    console.log("initiated", hash );
    axios.get("https://paxful.com/wallet/pay", {
      merchant:"onxQZvaVQZq", 
      apikey:"e4sDZyCdWYBTcA6iuIR09ddgZCEOgEAq",
      apiseal:hash,
      nonce:1386178459,
      to: "1CkSCqyWGtVjok5A5xeGKKyMvpeZMnfEbq",
      amount: 1,
    }).then(function(err){
      console.log("ERROR", err)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>PAXFUL TEST</h1>
          <button onClick={() => payMe()}>PAGAME</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
